server:
  port: 7070
spring:
  application:
    name: equinox
endpoints.health.sensitive: false
management.security.enabled: false
server.tomcat.max-threads: 5

turbine:
  aggregator:
    clusterConfig: SAMPLE-HYSTRIX-AGGREGATE
  appConfig: SAMPLE-HYSTRIX-AGGREGATE
usa:
  states:
    -
     name: California
     train: http://api.bart.gov/api/route.aspx?cmd=routes&key=MW9S-E7SL-26DU-VV8V&json=y
    -
     name: Oregon
     train: http://api.bart.gov/api/route.aspx?cmd=routes&key=MW9S-E7SL-26DU-VV8V&json=y
